# Generated by Django 6.0.7 on 2026-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
